In [29]:
import pandas as pd

df = pd.read_csv('./train.csv')
# df.groupby('Id')
grouped = df.groupby('Id')
grouped.count()

           Image
Id
new_whale    810
w_0013924      3
w_001ebbc      1
w_002222a      2
w_002b682      1
w_002dc11      1
w_0087fdd      2
w_008c602      1
w_009dc00      2
w_00b621b      2
w_00c4901      1
w_00cb685      3
w_00d8453      1
w_00fbb4e      2
w_0103030      1
w_010a1fa      2
w_011d4b5      2
w_0122d85      1
w_01319fa      1
w_0134192      1
w_013bbcf      1
w_014250a      2
w_014a645      1
w_0156f27      1
w_015c991      1
w_015e3cf      1
w_01687a8      2
w_0175a35      1
w_018bc64      1
w_01a4234      1
...          ...
w_fe5e78b      3
w_fe6617a      2
w_fe6c1f3      1
w_fe6f08d      1
w_fe8233d      1
w_fe87f0a      2
w_fe922c3      1
w_fe95ab8      4
w_fe96bef      1
w_fea7fe6      9
w_feab6f3      1
w_febafc1      3
w_fec1fb5      1
w_fec6413      1
w_fed0031      2
w_ff1b64c      5
w_ff2c4a4      1
w_ff2ca5c      1
w_ff39e03      1
w_ff5538f      1
w_ff70408      4
w_ff7630a      5
w_ff94ad6      1
w_ffa7427      3
w_ffa78a5      5
w_ffb4e3d      2
w_ffbd74c      2
w_ffcd98e      2
w_ffda8b2      4
w_ffdab7a      1

[4251 rows x 1 columns]

In [28]:
# grouped.groups
ng = grouped.ngroup()
# grouped.hist


df['class'] = ng
df

             Image         Id  class
0     00022e1a.jpg  w_e15442c   3741
1     000466c4.jpg  w_1287fbc    310
2     00087b01.jpg  w_da2efe0   3613
3     001296d5.jpg  w_19e5482    418
4     0014cfdf.jpg  w_f22f3e3   4012
5     0025e8c2.jpg  w_8b1ca89   2332
6     0026a8ab.jpg  w_eaad6a8   3889
7     0031c258.jpg  new_whale      0
8     0035632e.jpg  w_3d0bc7a    991
9     0037e7d3.jpg  w_50db782   1341
10    00389cd7.jpg  w_2863d51    651
11    0042dcc4.jpg  w_6dc7db6   1811
12    0042ea34.jpg  w_968f2ca   2530
13    00467ae9.jpg  w_fd1cb9d   4197
14    004a97f3.jpg  w_60759c2   1589
15    004c5fb9.jpg  w_ab6bb0a   2862
16    005c57e7.jpg  w_79b42cd   2030
17    006d0aaf.jpg  w_c9ba30c   3336
18    0078af23.jpg  w_e6ec8ee   3834
19    007c3603.jpg  new_whale      0
20    00863b8c.jpg  new_whale      0
21    008809b5.jpg  w_7e5cc5e   2104
22    008baccf.jpg  w_ab6db0f   2863
23    0091c92b.jpg  w_bc8d634   3140
24    009dca38.jpg  w_b59c523   3013
25    00a29f63.jpg  w_2850471    648
26    00aa021c.jpg  new_whale      0
27    00ab018e.jpg  w_51969d2   1355
28    00ac0e86.jpg  w_4be8a3e   1266
29    00acb5a9.jpg  w_c0cfd5b   3201
...            ...        ...    ...
9820  ff2d0d82.jpg  new_whale      0
9821  ff3509c0.jpg  w_8ba2066   2341
9822  ff38054f.jpg  w_6734e40   1705
9823  ff3c2c25.jpg  w_f5eb6c6   4071
9824  ff3f151f.jpg  w_9d5f5cc   2648
9825  ff421460.jpg  w_a16b600   2698
9826  ff4bb3a4.jpg  w_2d99a0c    741
9827  ff5a5ed4.jpg  w_f3bd33a   4035
9828  ff6946b4.jpg  w_17ee910    389
9829  ff6c1a92.jpg  w_4f0676a   1309
9830  ff6d6894.jpg  w_b426ff3   2995
9831  ff7247f6.jpg  w_41afa58   1082
9832  ff8b2ad0.jpg  w_0f20cbc    256
9833  ff92447f.jpg  w_372ae75    898
9834  ff9d60a3.jpg  w_eb0a6ed   3896
9835  ffa6b9ac.jpg  w_edf5f77   3941
9836  ffa78ccc.jpg  w_89d9c03   2305
9837  ffb71ac2.jpg  new_whale      0
9838  ffbaa734.jpg  w_a190b3b   2703
9839  ffbca206.jpg  w_73b26b7   1918
9840  ffc0b437.jpg  w_ace8c54   2880
9841  ffc6986f.jpg  w_fce6ab2   4189
9842  ffcfd124.jpg  w_41a260a   1080
9843  ffd01d82.jpg  w_6249155   1618
9844  ffd1e7aa.jpg  new_whale      0
9845  ffe5c306.jpg  w_2ceab05    732
9846  ffeaa7a4.jpg  w_b067417   2942
9847  ffecec63.jpg  w_8b56cb1   2337
9848  fff04277.jpg  w_2dcbf82    746
9849  fffd4260.jpg  w_b9bfd4e   3088

[9850 rows x 3 columns]